# Generated by Django 3.2.5 on 2022-10-21 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='seller_id',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Application.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
