# Generated by Django 3.2.5 on 2022-10-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_auto_20221021_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_id',
        ),
    ]
