# Generated by Django 3.2.5 on 2022-10-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_remove_product_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
